version: "3.1"

services:
  todo-mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: todo_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - 3306:3306
